---
- name: Centos | installing lvm2 and sg3_utils
  ansible.builtin.package:
    name:
      - lvm2
      - sg3_utils
    state: present
  become: true
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success

- name: Amazon tasks
  ansible.builtin.include_tasks: amazon.yml
  when: ansible_system_vendor == 'Amazon EC2'

- name: Centos | debug lvg
  ansible.builtin.debug:
    var: lv
    verbosity: 3
  loop: "{{ lookup('subelements', lvm_groups, 'lvnames', {'skip_missing': True}, wantlist=True) }}"
  loop_control:
    loop_var: lv

- name: Centos | install xfs tools
  ansible.builtin.package:
    name: "xfsprogs"
    state: "present"
  become: true
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success
  loop: "{{ lookup('subelements', lvm_groups, 'lvnames', {'skip_missing': True}, wantlist=True) }}"
  loop_control:
    loop_var: lv
  when:
    - lv.1 is defined
    - lv.1 != "None"
    - lv.1.filesystem is defined
    - lv.1.filesystem == "xfs"
    - lv.1.create is defined
    - lv.1.create|bool

- name: Centos | check for scsi adapters
  ansible.builtin.find:
    paths: "/sys/class/scsi_host"
    file_type: any
  become: true
  register: scsi_adapters

- name: Centos | scsi adapter matched
  when: scsi_adapters.matched > 0
  block:
    - name: Centos | installing sg3_utils
      ansible.builtin.package:
        name: sg3_utils
        state: present
      register: __pkg_result
      retries: 12
      delay: 10
      until: __pkg_result is success
      become: true

    - name: Centos | checking for scsi devices
      ansible.builtin.command: sg_scan
      become: true
      register: scsi_devices
      changed_when: false

    - name: Centos | rescanning for new disks
      ansible.builtin.command: "{{ rescan_scsi_command }}"
      become: true
      changed_when: false
      when: scsi_devices.stdout|length > 0

    - name: Centos | rescanning for resized disks
      ansible.builtin.command: "{{ rescan_scsi_command }} -s"
      become: true
      changed_when: false
      when: scsi_devices.stdout|length > 0
