---
- name: REDHAT | Install requirements
  ansible.builtin.package:
    name:
      - lvm2
      - sg3_utils
    state: present
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success

- name: Centos | install xfs tools
  ansible.builtin.package:
    name: "xfsprogs"
    state: "present"
  become: true
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success
  loop: "{{ lookup('subelements', lvm_groups, 'lvnames', {'skip_missing': True}, wantlist=True) }}"
  loop_control:
    loop_var: lv
  when:
    - lv.1 is defined
    - lv.1 != "None"
    - lv.1.filesystem is defined
    - lv.1.filesystem == "xfs"
    - lv.1.create is defined
    - lv.1.create|bool
# - name: centos | debug lvg
#   ansible.builtin.debug:
#     var: lv
#     verbosity: 3
#   loop: "{{ lookup('subelements', lvm_groups, 'lvnames', {'skip_missing': True}, wantlist=True) }}"
#   loop_control:
#     loop_var: lv
